### ISSUE TITLE
Thanks for the screenshots!  Added a new feature today that  you may be interested in...

### ISSUE THREAD

**Issue by PySimpleGUI** [enveezee/ptsg#2]
I ![image](https://user-images.githubusercontent.com/46163555/190529613-6955339a-0e23-4fce-81aa-6bde86bfcbd5.png) seeing screenshots like yours in readme files!  They grab visitors' attention right away.  

This evening I added a feature to PySimpleGUI on GitHub that will fit well with applications like yours where something is drawn and then the user may want to save an image of what was drawn.

The addition was a method available to all elements:
`save_element_screenshot_to_disk`

I did a super quick test for fun.  1 line of code for a Button, and 2 lines of code in the event loop:
```python
            if event == 'Save':
                self.window['_canvas_'].save_element_screenshot_to_disk('saved.jpg')
```

![image](https://user-images.githubusercontent.com/46163555/190530525-03acfb56-658b-43a3-bf73-4d25ab177be0.png)

This is the image saved to disk.

![saved](https://user-images.githubusercontent.com/46163555/190530556-c1529629-aef9-4e8f-90a6-1c7a9f63295f.jpg)

It's a new feature that will hopefully work out in the long-run.  There have been tricky problems with image capture so we'll see how it goes.  

I enjoyed seeing what you built.  Thanks for sharing it.

**Comment by enveezee** [comment]
Well as I'm sure you've gathered I only dabble with this stuff, but I do appreciate people taking interest in things I tool around with and sharing their experiences and ideas. I'd say having a comment directly from the developer of PySimpleGUI is a good endorsement. 

I found your work to be quite interesting as I loathe GUI coding and PySimpleGUI does make it simple enough to do simple things, but as I'm sure you know there are gray areas where some things you could do with a native tkinter or such are a lot more complicated from PySimpleGUI. I am not sure I'd actually use it for more than something I'm just trying to hack together quickly for a simple purpose. 

You could of course issue a pull request for your modifications as it seems like a useful feature for some possible use cases for such a simple test jig like this. It would be trivial for me to add it, but it was after all, your idea. 

I never did even get as far with reptangles as I did with the this test jig I was using to help me design it, because I was hitting a brick wall trying to figure out how to sew together my bits of code and get the GUI functional. However this did turn out to be a neat little example of what you could do with these libraries. I think I got a little too idealistic trying to make it easy to modify the layout and make use of this simple class example in a flexible kind of way, it makes the code harder to understand.
